- .github/configs/cr.yaml
- .github/workflows/publish.yaml
> Add publish helm chart to gh-pages function

- .github/configs/cr.yaml
- .github/workflows/publish.yaml
fix trigger from master to main 👍🏻
> fix trigger from master to main 👍🏻 

- index.html
> add fix html file

- charts/node-red/Chart.yaml
- charts/node-red/templates/deployment.yaml
add image registry to template
> add image registry to template

- README.md
- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/NOTES.txt
- charts/node-red/templates/deployment.yaml
- charts/node-red/templates/npmrc-cm.yaml
- charts/node-red/values.yaml
Add the option to configure custom npm registry
> Add custom npmrc

- .github/workflows/lint-and-test.yml
- DCO
- README.md
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> chore: docs: align docs to new location

- index.html
> chore: docs: change helm chart

- README.md
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> feature: version: update node-red version to 2.0.6-12

- README.md
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> chore: docs: add sources

- artifacthub-repo.yml
> feat: Verified Publisher

- README.md
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> chore: fix readme links

- artifacthub-repo.yml
> fix: fix name

- README.md
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> fix: fix default version in readme

- .github/renovate.json
> feat: add renovate.json

- README.md
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> fix: bump version in charts

- .github/workflows/publish.yaml
- README.md
> chore: update pipeline

- .github/workflows/lint-and-test.yml
- .github/workflows/ossf-scorecard-action.yaml
- .github/workflows/publish.yaml
feat: fix actions with renovate annotation
> feat: fix actions with renovate annotation

- SECURITY.md
> docs: add SECURITY file

- charts/node-red/Chart.yaml
> chore: trigger release

- .github/CODEOWNERS
- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/_helpers.tpl
- charts/node-red/templates/deployment.yaml
- charts/node-red/templates/npmrc-cm.yaml
> feat: making ConfigMap name unique

- charts/node-red/Chart.yaml
- charts/node-red/README.md
> chore: update app version

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/README.md.gotmpl
- charts/node-red/templates/_helpers.tpl
- charts/node-red/templates/certificates.yaml
- charts/node-red/values.yaml
> feat: adding support for cert-manager certificates

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/values.yaml
> feat: add extra volume support

- .github/workflows/ci.yaml
- Dockerfiles/Dockerfile
- Dockerfiles/Makefile
> feat: add custom node-red container image

- .github/workflows/build-docker-images.yaml
> feat: add write permission to pipeline

- .github/workflows/build-docker-images.yaml
> fix: remove permission on release job

- Dockerfiles/Dockerfile
- charts/node-red/values.yaml
> Passport oauth2

- Dockerfiles/Dockerfile
> feat: adding npm nodes

- Dockerfiles/Dockerfile
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> Version230

- Dockerfiles/Dockerfile
- Dockerfiles/Makefile
> feat: fix makefile version

- Dockerfiles/Dockerfile
> feat: fix Dockerfile var name

- charts/node-red/Chart.yaml
- charts/node-red/README.md
> fix: remove broken chart 0.8.0

- Dockerfiles/Makefile
> fix: add version to push in Makefile

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/values.yaml
> feat: adding optional value initContainers

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
> fix: indent of initContainers

- .github/workflows/lint-and-test.yml
- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/values.yaml
> feat: add support for custom settings.js

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
> feat: add optional prometheus support for node-red

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/values.yaml
> fix: add annotation support for deployment manifest

- .github/workflows/lint-and-test.yml
- charts/node-red/.helmignore
- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/README.md.gotmpl
- charts/node-red/scripts/flow_refresh.sh
- charts/node-red/templates/deployment.yaml
- charts/node-red/templates/sidecar-cm.yaml
- charts/node-red/tests/deployment_test.yaml
- charts/node-red/tests/flow_refresh_cm_test.yaml
- charts/node-red/tests/values/sidecar_values.yaml
- charts/node-red/values.yaml
> feat: add sidecar for flow reload

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/tests/deployment_test.yaml
- charts/node-red/tests/values/sidecar_values.yaml
- charts/node-red/values.yaml
> fix: fix defaultMode on refresh script

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
> fix: if condition on volume

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/tests/deployment_test.yaml
> fix: add slash to folder value

- charts/node-red/Chart.yaml
- charts/node-red/templates/deployment.yaml
- charts/node-red/values.yaml
> fix: remove initContainer and work with runAsUser and fsGroup

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/values.yaml
> fix: basic-auth support for servicemonitor

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/_helpers.tpl
- charts/node-red/templates/deployment.yaml
- charts/node-red/templates/sidecar-cm.yaml
- charts/node-red/tests/flow_refresh_cm_test.yaml
> fix: sidecar ConfigMapName

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/values.yaml
> feat: add option to add addition pod labels to deployment

- README.md
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> feat: update node-red to 3.0.0

- charts/node-red/Chart.yaml
- charts/node-red/README.md
> chore: update node-red to 3.0.2

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/values.yaml
feat: add Trivy suggestions to helm chart values
> feat: add Trivy suggestions to helm chart values

- .github/workflows/lint-and-test.yml
> feat: add trivy support

- .github/workflows/lint-and-test.yml
> chore: pin version of github/codeql-action/upload-sarif

- .github/workflows/ossf-scorecard-action.yaml
- README.md
> feat: add OSSF badge

- .github/workflows/publish.yaml
- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/README.md.gotmpl
> chore: add oci registry support

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/values.yaml
> feat: set default replica to 1 and remove option in values.yaml

- .github/workflows/publish.yaml
> fix: change way to capture digest from helm push

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/npmrc-cm.yaml
- charts/node-red/values.yaml
> feat: add option for custom content in npmrc file

- Makefile
> feat: add Makefile to start some basic automation.

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
> fix: fix indentation of the deployment.yaml env field

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
> fix: indentation of env vars of main container

- .github/workflows/publish.yaml
- charts/node-red/Chart.yaml
- charts/node-red/README.md
> fix: add -y to cosign command

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/sidecar-cm.yaml
- charts/node-red/tests/flow_refresh_cm_test.yaml
> fix: add missing quotes to create valid yaml

- charts/node-red/Chart.yaml
- charts/node-red/templates/service.yaml
- charts/node-red/values.yaml
https://github.com/SchwarzIT/node-red-chart/issues/264
> feat: adds annotations to service object

- .github/workflows/lint-and-test.yml
- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/deployment.yaml
- charts/node-red/values.yaml
Add ability to tweak terminationGracePeriodSeconds and liveness/readiness probes.
> Tweakable terminationGracePeriodSeconds, liveness/readiness probes

- charts/node-red/Chart.yaml
- charts/node-red/templates/certificates.yaml
> Fix error when enabling certificate

- .github/workflows/publish.yaml
- .github/workflows/update-docs.yaml
- charts/node-red/Chart.yaml
> feat: auto helm-doc and update node-red

- .github/workflows/update-docs.yaml
> feat: auto helm-doc

- charts/node-red/Chart.yaml
- charts/node-red/README.md
- charts/node-red/templates/clusterrole.yaml
- charts/node-red/templates/clusterrolebinding.yaml
- charts/node-red/templates/role.yaml
- charts/node-red/templates/rolebinding.yaml
- charts/node-red/values.yaml
> feat: add rbac support to disable the creation of roles and rolebindings

- charts/node-red/Chart.yaml
- charts/node-red/README.md
> chore: Update to Node-Red image to 3.1.9

- .github/dependabot.yml
> feat: add dependabot support and check quality

- .github/workflows/publish.yaml
- .github/workflows/update-docs.yaml
> fix: helm-docs

- charts/node-red/Chart.yaml
Bumped node version to latest. Seems to be working fine on my cluster.
> Update Node-RED to version 4.0.9
